const BBR_URL = "https://www.basketball-reference.com";

const PLAYERS: { [key: string]: string } = {
  prestja01: "Jason Preston",
  harriga01: "Gary Harris",
  cartevi01: "Vince Carter",
  hamptrj01: "R.J. Hampton",
  gordoaa01: "Aaron Gordon",
  clarkga01: "Gary Clark",
  teaguje01: "Jeff Teague",
  fournev01: "Evan Fournier",
  cartewe01: "Wendell Carter Jr.",
  porteot01: "Otto Porter Jr.",
  wagnefr01: "Franz Wagner",
  vucevni01: "Nikola Vucevic",
  aminual01: "Al-Farouq Aminu",
  nworajo01: "Jordan Nwora",
  ennisja01: "James Ennis",
  reedpa01: "Paul Reed",
  hortota01: "Talen Horton-Tucker",
  fultzma01: "Markelle Fultz",
  simmojo02: "Jonathon Simmons",
  edwarca01: "Carsen Edwards",
  maxeyty01: "Tyrese Maxey",
  martija01: "Jarell Martin",
  johnsda04: "Dakari Johnson",
  harvety01: "Tyler Harvey",
  purviro01: "Rodney Purvis",
  mozgoti01: "Timofey Mozgov",
  grantje02: "Jerian Grant",
  biyombi01: "Bismack Biyombo",
  martico01: "Cody Martin",
  madarya01: "Yam Madar",
  jacksju02: "Justin Jackson",
  vandeja01: "Jarred Vanderbilt",
  paytoel01: "Elfrid Payton",
  pasecan01: "Anzejs Pasecniks",
  rabbiv01: "Ivan Rabb",
  rosste01: "Terrence Ross",
  ibakase01: "Serge Ibaka",
  wilcocj01: "C.J. Wilcox",
  marblde01: "Devyn Marble",
  careyve01: "Vernon Carey Jr.",
  napiesh01: "Shabazz Napier",
  meeksjo01: "Jodie Meeks",
  handsja01: "Jaylen Hands",
  oladivi01: "Victor Oladipo",
  ilyaser01: "Ersan Ilyasova",
  sabondo01: "Domantas Sabonis",
  laymaja01: "Jake Layman",
  cunnija01: "Jared Cunningham",
  fryech01: "Channing Frye",
  jennibr01: "Brandon Jennings",
  harrito02: "Tobias Harris",
  harrijo01: "Joe Harris",
  harklma01: "Maurice Harkless",
  oquinky01: "Kyle O'Quinn",
  brazdig01: "Ignas Brazdeikis",
  timmaja01: "Janis Timma",
  ridnolu01: "Luke Ridnour",
  randoan01: "Anthony Randolph",
  rakovmi01: "Milovan Rakovic",
  saricda01: "Dario Saric",
  hernawi01: "Willy Hernangomez",
  foxde01: "De'Aaron Fox",
  afflaar01: "Arron Afflalo",
  lambdo01: "Doron Lamb",
  udrihbe01: "Beno Udrih",
  redicjj01: "J.J. Redick",
  ayongu01: "Gustavo Ayon",
  smithis01: "Ish Smith",
  warriha01: "Hakim Warrick",
  mcrobjo01: "Josh McRoberts",
  eyengch01: "Christian Eyenga",
  harrial01: "Al Harrington",
  osbyro01: "Romero Osby",
  iwundwe01: "Wesley Iwundu",
  kurucro01: "Rodions Kurucs",
  howardw01: "Dwight Howard",
  duhonch01: "Chris Duhon",
  clarkea01: "Earl Clark",
  richaja01: "Jason Richardson",
  anderry01: "Ryan Anderson",
  davisgl01: "Glen Davis",
  wafervo01: "Von Wafer",
  bassbr01: "Brandon Bass",
  harpeju01: "Justin Harper",
  crabbal01: "Allen Crabbe",
  arenagi01: "Gilbert Arenas",
  turkohe01: "Hedo Turkoglu",
  lewisra02: "Rashard Lewis",
  pietrmi01: "Mickael Pietrus",
  gortama01: "Marcin Gortat",
  mirotni01: "Nikola Mirotic",
};
const Player = (props: { id: string; idx: number }) => (
  <div>
    <a
      href={`${BBR_URL}/players/${props.id.slice(0, 1)}/${props.id}.html`}
      target="blank"
      className="underline hover:opacity-75"
    >
      {props.idx >= 1 && "=>  "}
      {PLAYERS[props.id]}
    </a>
  </div>
);

export default Player;
